logo_image: /uploads/pfp-1024x892-v2.png
logo_white: /assets/img/logo-pfp-white.png
favicon_image: /uploads/pfp-1024x892-v2.png
date_image: 'http://via.placeholder.com/40x110/'
urgence_image: 'http://via.placeholder.com/40x110/FF0000'
sidebar_size_number: 400
progress_bar_color: '#671c3d'
police:
  googlefont_url: >-
    https://fonts.googleapis.com/css2?family=Josefin+Sans:ital,wght@0,100;0,200;0,300;0,400;0,423;0,500;0,600;0,700;1,100;1,200;1,300;1,400;1,423;1,500;1,600;1,700&family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap
sidebar:
  title: '<b>COVID-19 :</b> Plus que jamais, nous avons besoins de vous !'
  subtitle:
  gift_grid:
    once:
      activate: true
      texte:
      gift_url: 'https://faireundon.petitsfreresdespauvres.fr/?cid=125'
      amount1_number: 80
      amount2_number: 100
      amount3_number: 150
    regular:
      activate: false
      texte: Je fais un don chaque mois
      gift_url: >-
        https://faireundon.petitsfreresdespauvres.fr/ab?cids[]=106&cids[]=109&amount=8000&frequency=regular
      amount1_number: 15
      amount2_number: 20
      amount3_number: 30
  defiscalisation: >-
    75% du montant de mon don sont déductibles de l'Impôt sur le Revenu, dans la
    limite de 20% du revenu net imposable.
popup:
  cgu:
    titre: CGU
    contenu_html: <p>...</p>
  privacy:
    titre: Données personnelles
    contenu_html: ...
edito:
  people:
    face_image: /_site/uploads/pfp-1024x892-v2.png
    name:
    job:
  introduction:
    title_html: >-
      Coronavirus<br>Covid-19
    introduction_html: Mobilisés pour éviter la<br> mort sociale de nos aînés.
    contenu_html: >-
      Face aux mesures essentielles de confinement pour freiner la progression du virus, les personnes âgées déjà victimes d’une solitude insupportable, courent le risque d’un isolement total.
      <br><br>Les Petits Frères des Pauvres, qui luttent contre l’isolement des personnes âgées depuis 1946, ont une priorité aujourd’hui : maintenir les liens avec nos aînés, tout en respectant les consignes données par le gouvernement.
      <br><br>Retrouvez ici toute l’actualité des actions mises en place partout en France par nos équipes pour continuer à briser l’isolement des personnes âgées.