logo_image: /uploads/pfp-1024x892-v2.png
favicon_image: /uploads/pfp-1024x892-v2.png
date_image: 'http://via.placeholder.com/40x110/'
urgence_image: 'http://via.placeholder.com/40x110/FF0000'
sidebar_size_number: 400
progress_bar_color: '#671c3d'
police:
  googlefont_url: >-
    https://fonts.googleapis.com/css2?family=Josefin+Sans:ital,wght@0,100;0,200;0,300;0,400;0,423;0,500;0,600;0,700;1,100;1,200;1,300;1,400;1,423;1,500;1,600;1,700&family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap
sidebar:
  title: Donec tincidunt risus ac volutpat lacinia.
  subtitle: 'Neque porro quisquam est qui dolorem, ipsum quia dolor sit.'
  gift_grid:
    once:
      activate: true
      texte: Je fais un don
      gift_url: >-
        https://faireundon.petitsfreresdespauvres.fr/ab?cids[]=106&cids[]=109&amount=8000&frequency=once
      amount1_number: 100
      amount2_number: 250
      amount3_number: 500
    regular:
      activate: false
      texte: Je fais un don chaque mois
      gift_url: >-
        https://faireundon.petitsfreresdespauvres.fr/ab?cids[]=106&cids[]=109&amount=8000&frequency=regular
      amount1_number: 15
      amount2_number: 20
      amount3_number: 30
  defiscalisation: >-
    75% du montant de mon don sont déductibles de l'Impôt sur le Revenu, dans la
    limite de 20% du revenu net imposable.
popup:
  cgu:
    titre: Conditions générales d'utilisation
    contenu_html: <p>...</p>
  privacy:
    titre: Données personnelles
    contenu_html: ...
edito:
  people:
    face_image:
    name:
    job:
  introduction:
    title_html: >-
      <p><strong><em>Coronavirus Covid-19
      :&nbsp;</em></strong><strong><em>Mobilis&eacute;s pour &eacute;viter la
      mort sociale de nos a&icirc;n&eacute;s.</em></strong></p>
    introduction_html: >-
      <p><em>Face aux mesures essentielles de confinement pour freiner la
      progression du virus, les personnes &acirc;g&eacute;es d&eacute;j&agrave;
      victimes d&rsquo;une solitude insupportable, courent le risque d&rsquo;un
      isolement total. Les Petits Fr&egrave;res des Pauvres, qui luttent contre
      l'isolement des personnes &acirc;g&eacute;es depuis 1946, ont une
      priorit&eacute; aujourd'hui : maintenir les liens avec nos
      a&icirc;n&eacute;s, tout en respectant les consignes donn&eacute;es par le
      gouvernement. Retrouvez ici toute l'actualit&eacute; des actions mises en
      place partout en France par nos &eacute;quipes pour continuer &agrave;
      briser l'isolement des personnes &acirc;g&eacute;es.</em></p><p>&nbsp;</p>
    contenu_html: